% P2_run_global_tc_adcirc_block_meshes.m
% Optional OceanMesh2D runner generated by P1_build_adcirc_model_blocks_from_partitions.m
clearvars; clc; close all;

SCRIPT_DIR = fileparts(mfilename('fullpath'));
CATALOG_DIR = env_path('ADCIRC_BLOCK_CATALOG_ROOT', fullfile(SCRIPT_DIR, 'catalog'));
BLOCK_CSV = fullfile(CATALOG_DIR, 'global_tc_adcirc_blocks.csv');
BOUNDARY_DIR = fullfile(CATALOG_DIR, 'block_boundaries');
OUT_MESH_DIR = env_path('ADCIRC_MESH_OUTPUT_ROOT', fullfile(SCRIPT_DIR, 'output', 'adcirc_fort14_meshes'));
OUT_FIG_DIR = env_path('ADCIRC_MESH_FIGURE_ROOT', fullfile(SCRIPT_DIR, 'output', 'adcirc_mesh_figures'));
if exist(OUT_MESH_DIR, 'dir') ~= 7, mkdir(OUT_MESH_DIR); end

if exist(OUT_FIG_DIR, 'dir') ~= 7, mkdir(OUT_FIG_DIR); end

repo_dir = env_path('OCEANMESH2D_ROOT', find_parent_dir_named(SCRIPT_DIR, 'OceanMesh2D-Projection'));
addpath(genpath(fullfile(repo_dir, 'utilities')));
addpath(genpath(fullfile(repo_dir, 'datasets')));
addpath(genpath(fullfile(repo_dir, 'm_map')));
addpath(genpath(fullfile(repo_dir, 'Examples', 'Global_autofunction')));

assert(exist('geodata', 'class') == 8 || exist('geodata', 'file') == 2, 'OceanMesh2D geodata is not on path.');
assert(exist('meshgen', 'class') == 8 || exist('meshgen', 'file') == 2, 'OceanMesh2D meshgen is not on path.');

T = readtable(BLOCK_CSV, 'TextType', 'string');
selected_blocks = strings(0,1); % keep empty to process all blocks, or set e.g. ["ADC_WNP_01"]
if ~isempty(selected_blocks), T = T(ismember(T.block_id, selected_blocks), :); end

coastline_coarse = 'land_polygons';
coastline_fine = 'land_polygons';
dem_coarse = 'GEBCO_2025_sub_ice.nc';
fine_dem_dir = fullfile(repo_dir, 'datasets', 'fine_dem');

min_el_out = 1e3; max_el_out = 20e3; max_el_ns_out = 5e3;
min_el_in = 200; max_el_in = 5e3; max_el_ns_in = 500;
wl = 30; g = 0.25;

for i = 1:height(T)
    block_id = T.block_id(i);
    fprintf('\n===== [%d/%d] %s =====\n', i, height(T), block_id);
    outer = readtable(fullfile(BOUNDARY_DIR, block_id + "_outer_ring.csv"));
    inner = readtable(fullfile(BOUNDARY_DIR, block_id + "_inner_ring.csv"));
    bbox_outer = [outer.lon, outer.lat];
    bbox_inner = [inner.lon, inner.lat];
    [dem_fine, dem_info] = auto_select_fine_dem_by_point(T.lon(i), T.lat(i), fine_dem_dir, dem_coarse); %#ok<NASGU>
    gdat_out = geodata('shp', coastline_coarse, 'dem', dem_coarse, 'bbox', bbox_outer, 'h0', min_el_out, 'window', 10);
    fh_out = edgefx('geodata', gdat_out, 'fs', 3, 'max_el_ns', max_el_ns_out, 'max_el', max_el_out, 'dt', 5, 'g', g, 'wl', wl);
    gdat_in = geodata('shp', coastline_fine, 'dem', dem_fine, 'bbox', bbox_inner, 'h0', min_el_in, 'window', 10);
    fh_in = edgefx('geodata', gdat_in, 'fs', 6, 'max_el_ns', max_el_ns_in, 'max_el', max_el_in, 'dt', 5, 'g', g);
    rng(1.23456789);
    mshopts = meshgen('ef', {fh_out, fh_in}, 'bou', {gdat_out, gdat_in}, 'plot_on', 1, 'proj', 'lam');
    mshopts = mshopts.build;
    m = mshopts.grd;
    m = interp(m, {gdat_out, gdat_in}, 'mindepth', 1);
    m = lim_bathy_slope(m, 0.1, 0);
    m = bound_courant_number(m, 1.2, 0.5, 0, 10);
    if exist('make_bc_from_capsule_boundary', 'file') == 2
        m = make_bc_from_capsule_boundary(m, gdat_out, 'shore_tol', 0.1, 'min_open_edges', 10, 'bridge_gap_edges', 4, 'add_inner_islands', true, 'inner_ibtype', 21, 'plot_check', true);
    end
    outBase = fullfile(OUT_MESH_DIR, "ADCIRC_Block_Mesh_" + block_id);
    write(m, char(outBase), '14');
    save(char(outBase + ".mat"), 'm');
    fig = figure('Color', 'w', 'Visible', 'off');
    plot(m, 'type', 'resologmesh');
    title("ADCIRC block mesh " + block_id, 'Interpreter', 'none');
    exportgraphics(fig, char(fullfile(OUT_FIG_DIR, "ADCIRC_Block_Mesh_" + block_id + ".png")), 'Resolution', 180);
    close(fig);
end

function value = env_path(name, defaultValue)
value = strtrim(string(getenv(name)));
if strlength(value) == 0
    value = string(defaultValue);
end
value = char(value);
end

function root = find_parent_dir_named(startDir, targetName)
root = ''; d = char(startDir); targetName = char(targetName);
while true
    [parent, name] = fileparts(d);
    if strcmpi(name, targetName), root = d; return; end
    if isempty(parent) || strcmp(parent, d), return; end
    d = parent;
end
end
